# Site settings
title: C5W Adversary Emulation System
email: info@advemu.com
url: https://www.advemu.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Cyber 5W

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/cyber5w
  - title: facebook
    url: https://www.facebook.com/cyber5w/
  - title: linkedin
    url: https://www.linkedin.com/company/cyber5w/
  - title: Instagram
    url: https://www.instagram.com/cyber5w/
  - title: YouTube
    url: https://www.youtube.com/c/AliHadiC5W 


# Build settings
markdown: kramdown
permalink: pretty
