# Site settings
title: TARIQ
email: info@advemu.com
url: https://www.advemu.com
description: "Tariq is Cyber 5W Adversary Si/Emulation System which aims to simulate and emulate the behavior of various threat actors based on their real TTP. The idea is to create playbooks for threat actors where companies can use to test if their security posture is good enough for this type of threat actor. In other words, test defenses based on simulations, rather than fall a victim to a true threat actor."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Cyber 5W

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/cyber5w
  - title: facebook
    url: https://www.facebook.com/cyber5w/
  - title: linkedin
    url: https://www.linkedin.com/company/cyber5w/
  - title: Instagram
    url: https://www.instagram.com/cyber5w/
  - title: YouTube
    url: https://www.youtube.com/c/AliHadiC5W 


# Build settings
markdown: kramdown
permalink: pretty
